language: java
jdk: oraclejdk7
script: 
  - if [ ! -z "$TRAVIS_TAG" ]; then travis_wait 30 mvn install source:jar javadoc:jar site site:stage -DreleaseTesting; else travis_wait 30 mvn install -DreleaseTesting; fi

env:
  global:
  - secure: ZUzhWfpXJw/oAeDlUkDFkEJMT0T7kCN3d7ah8urkL2B0KFfKOqQagkbXkgvDa1SYud8VdcnoGa69LfkEr5IrdqW7R4bEYZAiN5swm4Z0iO8t53szVspm2f+O9jQ44O/sfOfpfLxWUUuhdc7Vbrszp+tSszxdPmssWL+f5a/mfWs=
  - secure: pmFymoI7qH0Kna3NkcHrqLiTVWKmrhwqA4Z9U6XLhWDQxcs5g94wCCKpGB6Lkz9mkvRxBRFpZZelnXJa9W9mnuVOMIa5tQfS5gBuaNXOe7AXXdc+Y2975OR9sSfvf16FxLFvNJILmZq+bpMLs+EXaQvjYQHW2O6OWZdLhAPVG6A=
  - secure: Xkeo8OXzlLE5lmcRlkmlO8fbZqyxdzxF/yOZJVa7wfENU60LNkqGj3H8RcxVEwFRLYVe0PHu1MbDQdPrLe61Kt1z2Xr2oG1qNAUF5vySzvNbAycYbrW6L2lfHD21WWMVSBgQb8RXW8PhWTjucO6sVTyk6IpcIvrP8AEzjeHWIZI=
  - secure: eHvhfklQU9n95JiJLfwAOsVj7QOYgLljhUyR7cJO0uT6U/CT86bFxpxwKVlUGPQof+l+a99vWHXBq/4MD5IeoaM5ioDvwm++x8W1IhD7LHHEVLD4dYHsRieNYFzXv9E4femSmZCl+xOA0/DyXDOHpEZD56U+N7GjVB5Sbzo3fNM=
  - secure: Bh5LAk8XQnJ885jc/Lli2fhPKDx0TNZRxcJMnNo96EgwOnD+Zhw+v3u/DMCgyyrRToM8Bkca/HktrlZaRTk2htsdKZZ3RHFMCXO0fXCgpcf+wkaSYDF/lnErpSJG3Lrz8ILxJPODsrGhjaIg2++79lwhsBYtpujc6UdxFhgpffc=

before_install:
  - wget -O ~/codacy-coverage-reporter-assembly.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/1.0.13/codacy-coverage-reporter-1.0.13-assembly.jar

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r build-reporting/target/coverage-reports/jacoco.xml
  - ./coverity_scan.sh

deploy:
  - provider: script
    script: mvn --settings .travis.settings.xml -X deploy
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    local_dir: target/staging
    github_token: $GITHUB_TOKEN
    on:
      tags: true
      branch: master
 